/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectoFINAL_jevg;

import java.awt.Image;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

/**
 *
 * @author user             //JEVG
 */
public class I_Menu extends javax.swing.JFrame 
{

    /**
     * Creates new form I_Menu
     */
    public I_Menu() 
    {
        initComponents();
        
        ImageIcon imagenmenu = new ImageIcon("FondoMenu.jpg");
        ImageIcon iconomenu = new ImageIcon(imagenmenu.getImage().getScaledInstance(FondoMenu.getWidth(),FondoMenu.getHeight(), Image.SCALE_DEFAULT));
        FondoMenu.setIcon(iconomenu);
        ImageIcon imagenIncio = new ImageIcon("Inicio.png");
        ImageIcon iconomenuInicio = new ImageIcon(imagenIncio.getImage().getScaledInstance(25,25,1));
        Inicio.setIcon(iconomenuInicio);
        //Agregar       
        ImageIcon imagenAgregar = new ImageIcon("Agregar.png");
        ImageIcon iconoAgregar = new ImageIcon(imagenAgregar.getImage().getScaledInstance(165,100,1));//.getScaledInstance(Agregar.getWidth(),Agregar.getHeight(), Image.SCALE_DEFAULT));
        Agregar.setIcon(iconoAgregar);
        ImageIcon imagenAgregarIm = new ImageIcon("AgregarIm.png");
        ImageIcon iconoAgregarIm = new ImageIcon(imagenAgregarIm.getImage().getScaledInstance(AgregarIm.getWidth(),AgregarIm.getHeight(), Image.SCALE_DEFAULT));
        AgregarIm.setIcon(iconoAgregarIm);
        //Listar       
        ImageIcon imagenListar = new ImageIcon("Listar.png");
        ImageIcon iconoListar = new ImageIcon(imagenListar.getImage().getScaledInstance(165,100,1));//.getScaledInstance(Listar.getWidth(),Listar.getHeight(), Image.SCALE_DEFAULT));
        Listar.setIcon(iconoListar);
        ImageIcon imagenListarIm = new ImageIcon("ListarIm.png");
        ImageIcon iconoListarIm = new ImageIcon(imagenListarIm.getImage().getScaledInstance(ListarIm.getWidth(),ListarIm.getHeight(), Image.SCALE_DEFAULT));
        ListarIm.setIcon(iconoListarIm);
        //Seleccionar       
        ImageIcon imagenSeleccionar = new ImageIcon("Seleccionar.png");
        ImageIcon iconoSeleccionar = new ImageIcon(imagenSeleccionar.getImage().getScaledInstance(160,100,1));//.getScaledInstance(Seleccionar.getWidth(),Seleccionar.getHeight(), Image.SCALE_DEFAULT));
        Seleccionar.setIcon(iconoSeleccionar);
        ImageIcon imagenSeleccionarIm = new ImageIcon("SeleccionarIm.png");
        ImageIcon iconoSeleccionarIm = new ImageIcon(imagenSeleccionarIm.getImage().getScaledInstance(SeleccionarIm.getWidth(),SeleccionarIm.getHeight(), Image.SCALE_DEFAULT));
        SeleccionarIm.setIcon(iconoSeleccionarIm);
        //Visualizar       
        ImageIcon imagenVisualizar = new ImageIcon("Visualizar.png");
        ImageIcon iconoVisualizar = new ImageIcon(imagenVisualizar.getImage().getScaledInstance(165,100,1));//.getScaledInstance(Visualizar.getWidth(),Visualizar.getHeight(), Image.SCALE_DEFAULT));
        Visualizar.setIcon(iconoVisualizar);
        ImageIcon imagenVisualizarIm = new ImageIcon("Camara.png");
        ImageIcon iconoVisualizarIm = new ImageIcon(imagenVisualizarIm.getImage().getScaledInstance(VisualizarIm.getWidth(),VisualizarIm.getHeight(), Image.SCALE_DEFAULT));
        VisualizarIm.setIcon(iconoVisualizarIm);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Inicio = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        Agregar = new javax.swing.JButton();
        AgregarIm = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        Listar = new javax.swing.JButton();
        ListarIm = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        SeleccionarIm = new javax.swing.JLabel();
        Seleccionar = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        Visualizar = new javax.swing.JButton();
        VisualizarIm = new javax.swing.JLabel();
        FondoMenu = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Inicio.setBackground(new java.awt.Color(0, 102, 102));
        Inicio.setFont(new java.awt.Font("Snap ITC", 1, 14)); // NOI18N
        Inicio.setForeground(new java.awt.Color(255, 255, 255));
        Inicio.setText("Inicio");
        Inicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InicioActionPerformed(evt);
            }
        });
        getContentPane().add(Inicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, 110, 40));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "<html><center><h2>Agregar Productos<html>", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SWComp", 1, 11), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setOpaque(false);

        Agregar.setOpaque(false);
        Agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(AgregarIm, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(206, 206, 206))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(Agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AgregarIm, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 170, 320));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "<html><center><h2>Listar Productos<html>", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SWComp", 1, 11), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel2.setOpaque(false);

        Listar.setOpaque(false);
        Listar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ListarIm, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Listar, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Listar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ListarIm, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, 170, 320));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "<html><center><h2>Seleccionar Productos<html>", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SWComp", 1, 11), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel3.setOpaque(false);

        Seleccionar.setOpaque(false);
        Seleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeleccionarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SeleccionarIm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(Seleccionar, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Seleccionar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SeleccionarIm, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 50, 170, 320));

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "<html><center><h2>Visualizar Productos<html>", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SWComp", 1, 11), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel5.setOpaque(false);

        Visualizar.setOpaque(false);
        Visualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VisualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Visualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(VisualizarIm, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 8, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Visualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(VisualizarIm, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 50, 180, 320));
        getContentPane().add(FondoMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 710, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void InicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InicioActionPerformed
        // TODO add your handling code here:
        H_Inicio inicio;  
        inicio=new H_Inicio();
        inicio.setVisible(true);
        inicio.setB_RegistroPrincipal(SFC_JEVG);
        dispose();  
    }//GEN-LAST:event_InicioActionPerformed

    private void AgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarActionPerformed
        // TODO add your handling code here:
        J_AgregarProducto AP;             
        AP = new J_AgregarProducto();
        AP.setI_Menu(this);
        AP.setB_RegistroPrincipal(SFC_JEVG);
        AP.setVisible(true);
       // /*
        J_VisualizarProdAgregado VPA;             
        VPA = new J_VisualizarProdAgregado();
        VPA.setI_Menu(this);
        VPA.setB_RegistroPrincipal(SFC_JEVG);
        VPA.setVisible(true);//*/
    
        
        
        this.setVisible(false);  
    }//GEN-LAST:event_AgregarActionPerformed

    private void ListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListarActionPerformed
        // TODO add your handling code here                
        /*K_ListarProductos LP;             
        try {
            LP = new K_ListarProductos();
        } catch (ParseException ex) {
            Logger.getLogger(I_Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
        //LP.setI_Menu(this);
       // LP.setB_RegistroPrincipal(SFC_JEVG);
       // LP.setVisible(true);*/
        
        K_ListarProductos LP;             
        LP = new K_ListarProductos();
        LP.setI_Menu(this);
        LP.setB_RegistroPrincipal(SFC_JEVG);
        LP.setVisible(true);
        this.setVisible(false); 
    }//GEN-LAST:event_ListarActionPerformed

    private void SeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeleccionarActionPerformed
        // TODO add your handling code here:
       /* L_SeleccionarProductos LP;
        LP=new L_SeleccionarProductos(Fridge);
        LP.setI_Menu(this);
        LP.setVisible(true);
        setVisible(false);*/
        
        N_SeleccionarProductos SP;              
        SP = new N_SeleccionarProductos();
        SP.setI_Menu(this);
        SP.setB_RegistroPrincipal(SFC_JEVG);
        SP.setVisible(true);
       // /*
        O_Tiendas T;             
        T = new O_Tiendas();
        T.setI_Menu(this);
        T.setB_RegistroPrincipal(SFC_JEVG);
        T.setVisible(true);
         
        dispose();
    }//GEN-LAST:event_SeleccionarActionPerformed

    private void VisualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VisualizarActionPerformed
        // TODO add your handling code here:
        L_VisualizarProductos VP;             
        VP = new L_VisualizarProductos();
        VP.setI_Menu(this);
        VP.setB_RegistroPrincipal(SFC_JEVG);
        VP.setVisible(true);
        this.setVisible(false); 
    }//GEN-LAST:event_VisualizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(I_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(I_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(I_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(I_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new I_Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Agregar;
    private javax.swing.JLabel AgregarIm;
    private javax.swing.JLabel FondoMenu;
    private javax.swing.JButton Inicio;
    private javax.swing.JButton Listar;
    private javax.swing.JLabel ListarIm;
    private javax.swing.JButton Seleccionar;
    private javax.swing.JLabel SeleccionarIm;
    private javax.swing.JButton Visualizar;
    private javax.swing.JLabel VisualizarIm;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    // End of variables declaration//GEN-END:variables
    B_RegistroPrincipal SFC_JEVG;
         
    public void setB_RegistroPrincipal(B_RegistroPrincipal I)
    {
        SFC_JEVG = I;
    }   
}
