/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectoFINAL_jevg;

import java.awt.Image;
import java.text.DateFormat;
import javax.swing.ImageIcon;
import java.text.ParseException;
import static javax.swing.JOptionPane.ERROR_MESSAGE;

//COMUNICACIÓN TCP/IP
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.Observable;
import java.util.Observer;
import javax.swing.JOptionPane;
import static proyectoFINAL_jevg.A_Proyecto2_JEVG.AgregarProducto;
import static proyectoFINAL_jevg.A_Proyecto2_JEVG.ListarProductos;
import static proyectoFINAL_jevg.A_Proyecto2_JEVG.SeleccionarProducto;
import static proyectoFINAL_jevg.A_Proyecto2_JEVG.VisualizarProductos;

/**
 *
 * @author user         //JEVG
 */
public class J_AgregarProducto extends javax.swing.JFrame implements Observer
{

    /**
     * Creates new form J_AgregarProducto
     */
    public J_AgregarProducto() 
    {
        initComponents();
        ImageIcon imagenmenu = new ImageIcon("FondoAgregarIzquierda.jpg");
        ImageIcon iconomenu = new ImageIcon(imagenmenu.getImage().getScaledInstance(Fondo.getWidth(),Fondo.getHeight(), Image.SCALE_DEFAULT));
        Fondo.setIcon(iconomenu);
        
        ImageIcon imagenMenuIcon = new ImageIcon("MenuIcon.png");
        ImageIcon iconoMenuIcon = new ImageIcon(imagenMenuIcon.getImage().getScaledInstance(30,30,1));
        Menu.setIcon(iconoMenuIcon);
        
        ImageIcon imagenAgregarIcon = new ImageIcon("AgregarIcon.png");
        ImageIcon iconoAgregarIcon = new ImageIcon(imagenAgregarIcon.getImage().getScaledInstance(AgregarIcon.getWidth(),AgregarIcon.getHeight(), Image.SCALE_DEFAULT));
        AgregarIcon.setIcon(iconoAgregarIcon);
        
        //COMUNICACIÓN TCP/IP
        this.getRootPane().setDefaultButton(this.Guardar);
        Z_Servidor s = new Z_Servidor(7000);
        s.addObserver(this);
        Thread t = new Thread(s);
        t.start();
        
        uno = new C_Producto("","","",0); dos = new C_Producto("","","",0);
        tres = new C_Producto("","","",0); cuatro = new C_Producto("","","",0);
        cinco = new C_Producto("","","",0); seis = new C_Producto("","","",0);
        siete = new C_Producto("","","",0); ocho = new C_Producto("","","",0);
        nueve = new C_Producto("","","",0); diez = new C_Producto("","","",0);
    }    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NombreProducto = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        FechaIntroduccion = new com.toedter.calendar.JDateChooser();
        FechaCaducidad = new com.toedter.calendar.JDateChooser();
        Guardar = new javax.swing.JButton();
        Limpiar = new javax.swing.JButton();
        Menu = new javax.swing.JButton();
        AgregarIcon = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(NombreProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 120, -1));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nombre del Producto");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Fecha de Introducción");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Fecha de Caducidad");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        FechaIntroduccion.setDateFormatString("dd-MM-yyyy");
        getContentPane().add(FechaIntroduccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 120, -1));

        FechaCaducidad.setDateFormatString("dd-MM-yyyy");
        getContentPane().add(FechaCaducidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 120, -1));

        Guardar.setBackground(new java.awt.Color(255, 255, 255));
        Guardar.setFont(new java.awt.Font("Sylfaen", 1, 11)); // NOI18N
        Guardar.setText("GUARDAR");
        Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarActionPerformed(evt);
            }
        });
        getContentPane().add(Guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, 100, -1));
        Guardar.getAccessibleContext().setAccessibleName("GUARDAR");

        Limpiar.setBackground(new java.awt.Color(255, 255, 255));
        Limpiar.setFont(new java.awt.Font("Sylfaen", 1, 11)); // NOI18N
        Limpiar.setText("LIMPIAR");
        Limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimpiarActionPerformed(evt);
            }
        });
        getContentPane().add(Limpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, 100, -1));

        Menu.setBackground(new java.awt.Color(0, 102, 102));
        Menu.setFont(new java.awt.Font("Snap ITC", 1, 14)); // NOI18N
        Menu.setForeground(new java.awt.Color(255, 255, 255));
        Menu.setText("Menú");
        Menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuActionPerformed(evt);
            }
        });
        getContentPane().add(Menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, 140, 53));
        getContentPane().add(AgregarIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 240, 140));
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuActionPerformed
        // TODO add your handling code here:
        menu.setVisible(true);
        dispose();        
    }//GEN-LAST:event_MenuActionPerformed

    private void LimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimpiarActionPerformed
        // TODO add your handling code here:
        NombreProducto.setText("");
    }//GEN-LAST:event_LimpiarActionPerformed

    private void GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarActionPerformed
        // TODO add your handling code here:
        
        if((NombreProducto.getText().length()>0) && FechaIntroduccion.getDate()!=null && FechaCaducidad.getDate()!=null)
       {     
           
           String Nombre;
           Nombre = NombreProducto.getText();
                      
          // SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
           SimpleDateFormat dateFormat = new SimpleDateFormat("dd-MM-yyyy");
           Date date1 = FechaIntroduccion.getDate();
           String FechaEntrada = dateFormat.format(date1);
           Date date2 = FechaCaducidad.getDate();
           String FechaCad = dateFormat.format(date2);
            
               C_Producto Aux;
               Aux = new C_Producto();
               Aux.AsignarNombre(Nombre);
               Aux.AsignarFechaEntrada(FechaEntrada);
               Aux.AsignarFechaCad(FechaEntrada);
               SFC_JEVG.AgregarProducto(Aux);
               //menu.setVisible(true);
               //dispose();*/
            switch(i)
                    {
                        case 1: uno = new C_Producto(Nombre,FechaEntrada,FechaCad,0); i++;                       
                        break;
                        case 2: dos = new C_Producto(Nombre,FechaEntrada,FechaCad,0); i++;
                        break;
                        case 3: tres = new C_Producto(Nombre,FechaEntrada,FechaCad,0); i++;
                        break;
                        case 4: cuatro = new C_Producto(Nombre,FechaEntrada,FechaCad,0); i++;
                        break;
                        case 5: cinco = new C_Producto(Nombre,FechaEntrada,FechaCad,0); i++;
                        break;
                        case 6: seis = new C_Producto(Nombre,FechaEntrada,FechaCad,0); i++;
                        break;
                        case 7: siete = new C_Producto(Nombre,FechaEntrada,FechaCad,0); i++;
                        break;
                        case 8: ocho = new C_Producto(Nombre,FechaEntrada,FechaCad,0); i++;
                        break;
                        case 9: nueve = new C_Producto(Nombre,FechaEntrada,FechaCad,0); i++;
                        break;
                        case 10: diez = new C_Producto(Nombre,FechaEntrada,FechaCad,0); i++;
                    } 
               ///*//COMUNICACIÓN TCP/IP
                String mensaje = "Nuevo Producto Agregado:  " +Nombre+"\nIntroducido el:  "+FechaEntrada+"\nCaduca el:  "+FechaCad+"\n\n";
              //  this.respuesta.append(mensaje);
                Zz_Cliente c = new Zz_Cliente(8000, mensaje);
                Thread t = new Thread(c);
                t.start();//*/
                
                
       } 
        else 
        {
            JOptionPane.showMessageDialog(this, "Llena Todos los Campos", "Error", JOptionPane.ERROR_MESSAGE+JOptionPane.YES_NO_OPTION, null);      
        }
        
        
        /*String Nombre,FechaEntrada, FechaCad;
        
        int Error=0;
        C_Producto Aux;
        Aux = new C_Producto();
        Nombre = NombreProducto.getText();
   
        
      //  String dia = Interger.toString(FechaIntroduccion.getCalendar().get(Calendar.DATE));
      //  FechaEntrada=FechaIntroduccion.getDate();
        
      //  SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
      //  Date fechaEntrada=dateFormat.parse(FechaEntrada);
	//Date fechaCad=dateFormat.parse(FechaCad);
       // int DiasCad =(int) ((fechaCad.getTime()-fechaEntrada.getTime())/86400000);
        
        if (Nombre.length()==0) //&& FechaIntroduccion.getDate()!=null && FechaCaducidad.getDate()!=null )
        {
            Error=Error+1;
        }
        if (Error==0){
            Aux.AsignarNombre(Nombre);
            Fridge.AgregarProducto(Aux);
            menu.setVisible(true);
            dispose();
        }
        else {
            JOptionPane.showMessageDialog(this, "Se ingreso informacion incorrecta", "Error", JOptionPane.ERROR_MESSAGE+JOptionPane.YES_NO_OPTION, null);
        }
        
        */
 
       /*if((NombreProducto.getText().length()>0) && FechaIntroduccion.getDate()!=null && FechaCaducidad.getDate()!=null)
       {                                    
           String Nombre;

           Nombre = NombreProducto.getText();
           //FechaEntrada = FechaIn.getText();
          // FechaCad = FechaCadu.getText();
         // SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
          //FechaEntrada = FechaIntroduccion.getDateFormatString();
         // FechaCad = FechaCaducidad.getDateFormatString();
         
           //fechaEntrada = FechaIntroduccion.getDate();
           DateFormat fechaEntrada = new SimpleDateFormat("dd/MM/yyyy");
           //fechaCad = FechaCaducidad.getDate();
           DateFormat fechaCad = new SimpleDateFormat("dd/MM/yyyy");
           
           String FechaEntrada = fechaEntrada.format(fechaEntrada);
           //String FechaEntrada = "" + fechaEntrada;
           //String FechaCad = "" + fechaCad;
           String FechaCad = fechaEntrada.format(fechaCad);
            
               C_Producto P;
               P = new C_Producto();
               P.AsignarNombre(Nombre);
               P.AsignarFechaEntrada(FechaEntrada);
               P.AsignarFechaCad(FechaCad);
               Fridge.AgregarProducto(P);
               menu.setVisible(true);
               dispose();
       }
/*        if((NombreProducto.getText().length()>0))
       {                                    
           String Nombre;

           Nombre = NombreProducto.getText();
                     
               C_Producto P;
               P = new C_Producto();
               P.AsignarNombre(Nombre);
               H_Inicio.AgregarProducto(P);
               menu.setVisible(true);
               dispose();
       }  */
        
    }//GEN-LAST:event_GuardarActionPerformed
    public static C_Producto uno; public static C_Producto dos;
    public static C_Producto tres; public static C_Producto cuatro;
    public static C_Producto cinco; public static C_Producto seis;
    public static C_Producto siete; public static C_Producto ocho;
    public static C_Producto nueve; public static C_Producto diez;
    int i=1;
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(J_AgregarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(J_AgregarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(J_AgregarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(J_AgregarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new J_AgregarProducto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AgregarIcon;
    private com.toedter.calendar.JDateChooser FechaCaducidad;
    private com.toedter.calendar.JDateChooser FechaIntroduccion;
    private javax.swing.JLabel Fondo;
    private javax.swing.JButton Guardar;
    private javax.swing.JButton Limpiar;
    private javax.swing.JButton Menu;
    private javax.swing.JTextField NombreProducto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
B_RegistroPrincipal SFC_JEVG;
I_Menu menu;
            
    public void setB_RegistroPrincipal(B_RegistroPrincipal i)
    {
        SFC_JEVG = i;
    }   
    public void setI_Menu(I_Menu m)
    {
        menu=m;
    }  
    
    //COMUNICACIÓN TCP/IP
    ///*@Override
    public void update(Observable o, Object arg) 
    {
       //this.respuesta.append((String) arg);
    }//*/

}
