/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectoFINAL_jevg;

import java.awt.Image;
import javax.swing.ImageIcon;

//vision artificial
import com.github.sarxos.webcam.Webcam;
import com.github.sarxos.webcam.WebcamPanel;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.GridLayout;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.image.BufferedImage;
import javax.swing.ImageIcon;


/**
 *
 * @author user                     //JEVG
 */
public class M_VisualizarProductos extends javax.swing.JFrame
{    
    BufferedImage OrigenImagen;
    BufferedImage DestinoImagen;
    ImageIcon Imagen;
    
    Webcam webcam;
    WebcamPanel Origen;
    /**
     * Creates new form M_VisualizarProductos
     */
    public M_VisualizarProductos() 
    {
        initComponents();
        
        ImageIcon imagen1 = new ImageIcon("Camara.png");
        ImageIcon icono1 = new ImageIcon(imagen1.getImage().getScaledInstance(Camara.getWidth(),Camara.getHeight(), Image.SCALE_DEFAULT));
        Camara.setIcon(icono1);
        
        // VISION ARTIFICIAL
        webcam= Webcam.getDefault();
        Origen = new WebcamPanel(webcam);

        Inferior.setLayout(new FlowLayout());

        Central.setLayout(new GridLayout(1,2));
        Central.add(Origen);
        Central.add(Destino);
        
        Destino.add(DestinoLabel);
        
      //  Captura.addActionListener(this);
      //  Gris.addActionListener(this);
      //  Monocromatico.addActionListener(this);
        
        
        new M_z_Reloj();   
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Menu = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        Camara = new javax.swing.JLabel();
        Central = new javax.swing.JPanel();
        Destino = new javax.swing.JPanel();
        DestinoLabel = new javax.swing.JLabel();
        Inferior = new javax.swing.JPanel();
        Captura = new javax.swing.JButton();
        Gris = new javax.swing.JButton();
        Monocromatico = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Menu.setBackground(new java.awt.Color(0, 102, 102));
        Menu.setFont(new java.awt.Font("Snap ITC", 1, 14)); // NOI18N
        Menu.setForeground(new java.awt.Color(255, 255, 255));
        Menu.setText("Menú");
        Menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "CAMARA DE VIGILANCIA", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 102, 102))); // NOI18N

        Camara.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Camara, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Camara, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Central.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "CAMARA WEB", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tw Cen MT", 1, 14), new java.awt.Color(0, 153, 153))); // NOI18N

        javax.swing.GroupLayout DestinoLayout = new javax.swing.GroupLayout(Destino);
        Destino.setLayout(DestinoLayout);
        DestinoLayout.setHorizontalGroup(
            DestinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 51, Short.MAX_VALUE)
        );
        DestinoLayout.setVerticalGroup(
            DestinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 196, Short.MAX_VALUE)
        );

        DestinoLabel.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout CentralLayout = new javax.swing.GroupLayout(Central);
        Central.setLayout(CentralLayout);
        CentralLayout.setHorizontalGroup(
            CentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CentralLayout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(Destino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(DestinoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 332, Short.MAX_VALUE)
                .addContainerGap())
        );
        CentralLayout.setVerticalGroup(
            CentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CentralLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Destino, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(DestinoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        Captura.setText("Capturar");
        Captura.setPreferredSize(new java.awt.Dimension(105, 23));
        Captura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CapturaActionPerformed(evt);
            }
        });

        Gris.setText("Gris");
        Gris.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GrisActionPerformed(evt);
            }
        });

        Monocromatico.setText("Monocromatico");
        Monocromatico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MonocromaticoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout InferiorLayout = new javax.swing.GroupLayout(Inferior);
        Inferior.setLayout(InferiorLayout);
        InferiorLayout.setHorizontalGroup(
            InferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InferiorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Monocromatico)
                .addGap(39, 39, 39)
                .addComponent(Gris, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(InferiorLayout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(Captura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        InferiorLayout.setVerticalGroup(
            InferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InferiorLayout.createSequentialGroup()
                .addComponent(Captura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(InferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Gris)
                    .addComponent(Monocromatico))
                .addContainerGap())
        );

        jLabel2.setText("CAPTURA");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(Menu, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Central, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(Inferior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Menu, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Central, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(Inferior, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel2)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuActionPerformed
        // TODO add your handling code here:
        menu.setVisible(true);
        dispose();
    }//GEN-LAST:event_MenuActionPerformed

    private void CapturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CapturaActionPerformed
        // TODO add your handling code here:
        DestinoImagen = webcam.getImage();
        Imagen = new ImageIcon(DestinoImagen);
        DestinoLabel.setIcon(Imagen);
        DestinoLabel.setIcon(Imagen);
    }//GEN-LAST:event_CapturaActionPerformed

    private void MonocromaticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MonocromaticoActionPerformed
        // TODO add your handling code here:
        int i,j;
        int Ancho, Alto;
        Color RGB;
        int Red, Green, Blue, Mono;
        Ancho = DestinoImagen.getWidth();
        Alto = DestinoImagen.getHeight();

        for(i=0; i<Ancho; i++ )
        {
            for(j=0; j<Alto; j++ )
            {
                RGB = new Color(DestinoImagen.getRGB(i, j));
                Red = RGB.getRed();
                Green = RGB.getGreen();
                Blue = RGB.getBlue();
                Mono = (Red+Green+Blue)/3;
                if(Mono>=128)
                {
                    DestinoImagen.setRGB(i, j, (Color.WHITE).getRGB());   
                }
                else
                {
                    DestinoImagen.setRGB(j, j, (Color.BLACK).getRGB());
                }
                Imagen = new ImageIcon(DestinoImagen);
                DestinoLabel.setIcon(Imagen);
            }
        }
    }//GEN-LAST:event_MonocromaticoActionPerformed

    private void GrisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GrisActionPerformed
        // TODO add your handling code here:
        int i,j;
        int Ancho, Alto;
        Color RGB, GRIS;
        int Red, Green, Blue, Gray;
        Ancho = DestinoImagen.getWidth();
        Alto = DestinoImagen.getHeight();

        for(i=0; i<Ancho; i++ )
        {
            for(j=0; j<Alto; j++ )
            {
                RGB = new Color(DestinoImagen.getRGB(i, j));
                Red = RGB.getRed();
                Green = RGB.getGreen();
                Blue = RGB.getBlue();
                Gray = (int)(((Red*0.3)+(Green*0.59)+(Blue*0.11)));
                GRIS = new Color(Gray, Gray, Gray);

                DestinoImagen.setRGB(i, j, GRIS.getRGB());
                Imagen = new ImageIcon(DestinoImagen);
                DestinoLabel.setIcon(Imagen);
            }
        } 
    }//GEN-LAST:event_GrisActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(M_VisualizarProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(M_VisualizarProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(M_VisualizarProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(M_VisualizarProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new M_VisualizarProductos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Camara;
    private javax.swing.JButton Captura;
    private javax.swing.JPanel Central;
    private javax.swing.JPanel Destino;
    private javax.swing.JLabel DestinoLabel;
    private javax.swing.JButton Gris;
    private javax.swing.JPanel Inferior;
    private javax.swing.JButton Menu;
    private javax.swing.JButton Monocromatico;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
 B_RegistroPrincipal H_Inicio;
 I_Menu menu;
    
    public void setB_RegistroPrincipal(B_RegistroPrincipal I)
    {
        H_Inicio = I;
    }   
    
    public void setI_Menu(I_Menu m)
    {
        menu=m;
    }
}
