/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectoFINAL_jevg;

import java.awt.Image;
import javax.swing.ImageIcon;

//COMUNICACIÓN TCP/IP   
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.Observable;
import java.util.Observer;
import javax.swing.JOptionPane;
/**
 *
 * @author user             //JEVG
 */
public class N_SeleccionarProductos extends javax.swing.JFrame implements Observer
{
    

    /**
     * Creates new form L_SeleccionarProductos
     */
    public N_SeleccionarProductos() 
    {
        initComponents();
        ImageIcon imagenMenuIcon = new ImageIcon("MenuIcon.png");
        ImageIcon iconoMenuIcon = new ImageIcon(imagenMenuIcon.getImage().getScaledInstance(30,30,1));
        Menu.setIcon(iconoMenuIcon);
        
        ImageIcon imagenmenu = new ImageIcon("FondoSeleccionar.jpg");
        ImageIcon iconomenu = new ImageIcon(imagenmenu.getImage().getScaledInstance(FondoSelect.getWidth(),FondoSelect.getHeight(), Image.SCALE_DEFAULT));
        FondoSelect.setIcon(iconomenu);
        
       //COMUNICACIÓN TCP/IP
        this.getRootPane().setDefaultButton(this.Seleccionar);
        Z_Servidor s = new Z_Servidor(9000);
        s.addObserver(this);
        Thread t = new Thread(s);
        t.start();
        
        
        SelectProd.addItem("Producto 1: "+Producto1); SelectProd.addItem("Producto 2: "+Producto2);
        SelectProd.addItem("Producto 3: "+Producto3); SelectProd.addItem("Producto 4: "+Producto4);
        SelectProd.addItem("Producto 5: "+Producto5); SelectProd.addItem("Producto 6: "+Producto6); 
        SelectProd.addItem("Producto 7: "+Producto7); SelectProd.addItem("Producto 8: "+Producto8);  
        SelectProd.addItem("Producto 9: "+Producto9); SelectProd.addItem("Producto 10: "+Producto10);  
        
       // TextoNombre.setText(J_AgregarProducto.uno.Nombre);
    }
    
    
     /*public L_SeleccionarProductos(B_RegistroPrincipal I)
     {
        Fridge=I;
        Productos=getProductos();
        initComponents();
        
    }
    
    public void Update(int Selected)
    {
        
        String []NombreCuentas;
        if (Productos.length==0)
        {
            TextoNombre.setEnabled(false);
        }
           
    }*/
String Producto1=J_AgregarProducto.uno.Nombre;  String Producto2=J_AgregarProducto.dos.Nombre; 
String Producto3=J_AgregarProducto.tres.Nombre;  String Producto4=J_AgregarProducto.cuatro.Nombre; 
String Producto5=J_AgregarProducto.cinco.Nombre; String Producto6=J_AgregarProducto.seis.Nombre;
String Producto7=J_AgregarProducto.siete.Nombre; String Producto8=J_AgregarProducto.ocho.Nombre;
String Producto9=J_AgregarProducto.nueve.Nombre; String Producto10=J_AgregarProducto.diez.Nombre;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDayChooser1 = new com.toedter.calendar.JDayChooser();
        ProdNombre = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Menu = new javax.swing.JButton();
        SelectProd = new javax.swing.JComboBox<>();
        Seleccionar = new javax.swing.JButton();
        FondoSelect = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ProdNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProdNombreActionPerformed(evt);
            }
        });
        getContentPane().add(ProdNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 159, -1));

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("PRODUCTOS SELECCIONABES");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Confirmación de Producto:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        Menu.setBackground(new java.awt.Color(0, 102, 102));
        Menu.setFont(new java.awt.Font("Snap ITC", 1, 14)); // NOI18N
        Menu.setForeground(new java.awt.Color(255, 255, 255));
        Menu.setText("Menú");
        Menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuActionPerformed(evt);
            }
        });
        getContentPane().add(Menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 130, 53));

        SelectProd.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                SelectProdItemStateChanged(evt);
            }
        });
        SelectProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelectProdActionPerformed(evt);
            }
        });
        getContentPane().add(SelectProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 78, 280, -1));

        Seleccionar.setText("Seleccionar");
        Seleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeleccionarActionPerformed(evt);
            }
        });
        getContentPane().add(Seleccionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, -1, -1));
        getContentPane().add(FondoSelect, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 290));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuActionPerformed
        // TODO add your handling code here:
        I_Menu M;  
        M = new I_Menu();
        M.setVisible(true);
        dispose();
 
    }//GEN-LAST:event_MenuActionPerformed

    private void SelectProdItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_SelectProdItemStateChanged
        // TODO add your handling code here:
        String Productos = (String) SelectProd.getSelectedItem();
        if(Productos.equals("Producto 1: "+Producto1)){ProdNombre.setText(Producto1);}
        if(Productos.equals("Producto 2: "+Producto2)){ProdNombre.setText(Producto2);}
        if(Productos.equals("Producto 3: "+Producto3)){ProdNombre.setText(Producto3);}
        if(Productos.equals("Producto 4: "+Producto4)){ProdNombre.setText(Producto4);}
        if(Productos.equals("Producto 5: "+Producto5)){ProdNombre.setText(Producto5);}
        if(Productos.equals("Producto 6: "+Producto6)){ProdNombre.setText(Producto6);}
        if(Productos.equals("Producto 7: "+Producto7)){ProdNombre.setText(Producto7);}
        if(Productos.equals("Producto 8: "+Producto8)){ProdNombre.setText(Producto8);}
        if(Productos.equals("Producto 9: "+Producto9)){ProdNombre.setText(Producto9);}
        if(Productos.equals("Producto 10: "+Producto10)){ProdNombre.setText(Producto10);}
        
    }//GEN-LAST:event_SelectProdItemStateChanged

    private void SelectProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelectProdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SelectProdActionPerformed

    private void ProdNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProdNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ProdNombreActionPerformed

    private void SeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeleccionarActionPerformed
        // TODO add your handling code here:
                     ///*//COMUNICACIÓN TCP/IP
                String mensaje = ProdNombre.getText();
              //this.respuesta.append(mensaje);
                Zz_Cliente c = new Zz_Cliente(10000, mensaje);
                Thread t = new Thread(c);
                t.start();//*/
    }//GEN-LAST:event_SeleccionarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(N_SeleccionarProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(N_SeleccionarProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(N_SeleccionarProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(N_SeleccionarProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new N_SeleccionarProductos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FondoSelect;
    private javax.swing.JButton Menu;
    private javax.swing.JTextField ProdNombre;
    private javax.swing.JButton Seleccionar;
    private javax.swing.JComboBox<String> SelectProd;
    private com.toedter.calendar.JDayChooser jDayChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
 B_RegistroPrincipal SFC_JEVG;
 I_Menu menu;
 
     public void setI_Menu(I_Menu M)
    {
        menu = M;
    }
      /*public void setB_RegistroPrincipal(B_RegistroPrincipal I)
    {
        Fridge = I;
    }   */
    // TextoNombre.setText(J_AgregarProducto.uno.Nombre);
    public void setB_RegistroPrincipal(B_RegistroPrincipal I)
    {
        SFC_JEVG = I;
        /*int NumProducto, i;
        String Productos[];
        SFC_JEVG = I;
        NumProducto=SFC_JEVG.ObtenerNumProducto();
        Productos=new String[NumProducto];
        for(i=0; i<NumProducto;i++)
        {
            Productos[i]=SFC_JEVG.ObtenerProducto(i).ObtenerNombre();
                
        }*/
        /*Productos[i]=J_AgregarProducto.uno.Nombre;
          Productos[i]=J_AgregarProducto.dos.Nombre;
          Productos[i]=J_AgregarProducto.tres.Nombre;
          Productos[i]=J_AgregarProducto.cuatro.Nombre;
          Productos[i]=J_AgregarProducto.cinco.Nombre;*/
    } 
    
        public void update(Observable o, Object arg) 
    {
       //this.respuesta.append((String) arg);
    }//*/
}

