/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectoFINAL_jevg;

import java.awt.Image;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Observable;
import java.util.Observer;
import javax.swing.ImageIcon;

public class O_Tiendas extends javax.swing.JFrame implements Observer {
ArrayList  <O_TiendaFrameObjetos> listaFisica = new ArrayList <O_TiendaFrameObjetos>();
ArrayList  <O_TiendaFrameObjetos> listaLinea = new ArrayList <O_TiendaFrameObjetos>();
ArrayList  <O_TiendaFrameObjetos> listaLocal = new ArrayList <O_TiendaFrameObjetos>();

    public O_Tiendas() {
        initComponents();
        
        ImageIcon imagenmenu = new ImageIcon("FondoTiendas.jpg");
        ImageIcon iconomenu = new ImageIcon(imagenmenu.getImage().getScaledInstance(FondoT.getWidth(),FondoT.getHeight(), Image.SCALE_DEFAULT));
        FondoT.setIcon(iconomenu);
        
        //this.getRootPane().setDefaultButton(this.btnEnviar);
        Z_Servidor s = new Z_Servidor(10000);
        s.addObserver(this);
        Thread t = new Thread(s);
        t.start();

          
             
    }

    public void mostrarTF()
    {
        String matrix [] [] = new String[listaFisica.size()][3]; 
        for(int i=0 ; i < listaFisica.size() ; i++)
        {
            matrix[i][0] = listaFisica.get(i).getProduct();
            matrix[i][1] = listaFisica.get(i).getNombre();
            matrix[i][2] = listaFisica.get(i).getPrecio();
        }    
        
        TiendasFisicas.setModel(new javax.swing.table.DefaultTableModel(
            matrix,
            new String [] {
                "PRODUCTO", "Nombre de la TIENDA", "PRECIO de COMPRA"
            }
        ));   
    }
    
      public void mostrarTL()
    {
        String matrix [] [] = new String[listaLinea.size()][3]; 
        for(int i=0 ; i < listaLinea.size() ; i++)
        {
            matrix[i][0] = listaLinea.get(i).getProduct();
            matrix[i][1] = listaLinea.get(i).getNombre();
            matrix[i][2] = listaLinea.get(i).getPrecio();
        }    
        
        TiendasLinea.setModel(new javax.swing.table.DefaultTableModel(
            matrix,
            new String [] {
                "PRODUCTO", "Nombre de la TIENDA", "PRECIO de COMPRA"
            }
        ));   
    }
      
      public void mostrarTLO()
    {
        String matrix [] [] = new String[listaLocal.size()][3]; 
        for(int i=0 ; i < listaLocal.size() ; i++)
        {
            matrix[i][0] = listaLocal.get(i).getProduct();
            matrix[i][1] = listaLocal.get(i).getNombre();
            matrix[i][2] = listaLocal.get(i).getPrecio();
        }    
        
        TiendasLocales.setModel(new javax.swing.table.DefaultTableModel(
            matrix,
            new String [] {
                "PRODUCTO", "Nombre de la TIENDA", "PRECIO de COMPRA"
            }
        ));   
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        VariablesTienda = new javax.swing.ButtonGroup();
        Tiendas = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        TFisica = new javax.swing.JRadioButton();
        TLinea = new javax.swing.JRadioButton();
        TLocal = new javax.swing.JRadioButton();
        Guardar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TiendasFisicas = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        NombreTienda = new javax.swing.JTextField();
        PrecioPoroducto = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtTexto = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        TiendasLinea = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        TiendasLocales = new javax.swing.JTable();
        Cerrar = new javax.swing.JButton();
        FondoT = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("FRM2");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setOpaque(false);

        Tiendas.add(TFisica);
        TFisica.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        TFisica.setText("Tienda FISICA");

        Tiendas.add(TLinea);
        TLinea.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        TLinea.setText("Tienda en LINEA");

        Tiendas.add(TLocal);
        TLocal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        TLocal.setText("Tienda LOCAL");

        Guardar.setBackground(new java.awt.Color(255, 255, 255));
        Guardar.setText("GUARDAR");
        Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TLocal)
                            .addComponent(TLinea))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Guardar)
                            .addComponent(TFisica))
                        .addGap(10, 26, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(Guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(TFisica)
                .addGap(18, 18, 18)
                .addComponent(TLinea)
                .addGap(18, 18, 18)
                .addComponent(TLocal)
                .addContainerGap())
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, -1, -1));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "TIENDAS FISICAS", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel3.setOpaque(false);

        TiendasFisicas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(TiendasFisicas);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(415, 35, -1, -1));

        jPanel4.setOpaque(false);

        txtTexto.setColumns(20);
        txtTexto.setRows(5);
        jScrollPane1.setViewportView(txtTexto);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Producto");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombre Tienda");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Precio Producto");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1)
                            .addComponent(PrecioPoroducto, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NombreTienda, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(jLabel1))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(jLabel2))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(jLabel3)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NombreTienda, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PrecioPoroducto, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, 220));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "TIENDAS EN LINEA", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel1.setOpaque(false);

        TiendasLinea.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        jScrollPane3.setViewportView(TiendasLinea);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(415, 261, -1, -1));

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "TIENDAS LOCALES", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel5.setOpaque(false);

        TiendasLocales.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        jScrollPane4.setViewportView(TiendasLocales);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 19, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 261, -1, -1));

        Cerrar.setBackground(new java.awt.Color(255, 255, 255));
        Cerrar.setText("CERRAR");
        Cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CerrarActionPerformed(evt);
            }
        });
        getContentPane().add(Cerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 50, -1, -1));
        getContentPane().add(FondoT, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarActionPerformed
         
        if(TFisica.isSelected()==true)
        {
        O_TiendaFrameObjetos TiendaFisica = new O_TiendaFrameObjetos(txtTexto.getText(),NombreTienda.getText(),PrecioPoroducto.getText());
        listaFisica.add(TiendaFisica);
        mostrarTF();   
        }
        else if(TLinea.isSelected()==true)
        {
        O_TiendaFrameObjetos TiendaLinea = new O_TiendaFrameObjetos(txtTexto.getText(),NombreTienda.getText(),PrecioPoroducto.getText());
        listaLinea.add(TiendaLinea);
        mostrarTL();   
        }
        else if(TLocal.isSelected()==true)
        {
        O_TiendaFrameObjetos TiendaFisica = new O_TiendaFrameObjetos(txtTexto.getText(),NombreTienda.getText(),PrecioPoroducto.getText());
        listaLocal.add(TiendaFisica);
        mostrarTLO();   
        }
        txtTexto.setText("");
        NombreTienda.setText("");
        PrecioPoroducto.setText("");  
        
                
// TODO add your handling code here:
          /*  String Nombre;
           Nombre = NombreProducto.getText();
                      
          // SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
           SimpleDateFormat dateFormat = new SimpleDateFormat("dd-MM-yyyy");
           Date date1 = FechaIntroduccion.getDate();
           String FechaEntrada = dateFormat.format(date1);
           Date date2 = FechaCaducidad.getDate();
           String FechaCad = dateFormat.format(date2);
            
               C_Producto Aux;
               Aux = new C_Producto();
               Aux.AsignarNombre(Nombre);
               Aux.AsignarFechaEntrada(FechaEntrada);
               Aux.AsignarFechaCad(FechaEntrada);
               SFC_JEVG.AgregarProducto(Aux); */
          

    }//GEN-LAST:event_GuardarActionPerformed

    private void CerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CerrarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_CerrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(O_Tiendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(O_Tiendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(O_Tiendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(O_Tiendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new O_Tiendas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cerrar;
    private javax.swing.JLabel FondoT;
    private javax.swing.JButton Guardar;
    private javax.swing.JTextField NombreTienda;
    private javax.swing.JTextField PrecioPoroducto;
    private javax.swing.JRadioButton TFisica;
    private javax.swing.JRadioButton TLinea;
    private javax.swing.JRadioButton TLocal;
    public static javax.swing.ButtonGroup Tiendas;
    private javax.swing.JTable TiendasFisicas;
    private javax.swing.JTable TiendasLinea;
    private javax.swing.JTable TiendasLocales;
    public static javax.swing.ButtonGroup VariablesTienda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea txtTexto;
    // End of variables declaration//GEN-END:variables

    
        B_RegistroPrincipal SFC_JEVG;
    I_Menu menu;
            
    public void setB_RegistroPrincipal(B_RegistroPrincipal i)
    {
        SFC_JEVG = i;
    }   
    public void setI_Menu(I_Menu m)
    {
        menu=m;
    }  
 
    //COMUNICACION TCP/IP
    @Override
    public void update(Observable o, Object arg) {
        
        this.txtTexto.append((String) arg);
    }
 
    
}
