/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectoFINAL_jevg;

/**
 *
 * @author user
 */
public class Z_LicenciaJEVG_CC extends javax.swing.JFrame {

    /**
     * Creates new form Z_LicenciaJEVG_CC
     */
    public Z_LicenciaJEVG_CC() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Regresar = new javax.swing.JButton();
        CC_JEVG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Regresar.setText("Inicio");
        Regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegresarActionPerformed(evt);
            }
        });
        getContentPane().add(Regresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 40, -1, -1));

        CC_JEVG.setFont(new java.awt.Font("Tw Cen MT", 0, 11)); // NOI18N
        CC_JEVG.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        CC_JEVG.setText("<html> <h2> <body style=»text-align: center;»>Attribution-NonCommercial-ShareAlike 4.0 International (CC BY-NC-SA 4.0)\n" +
            "    <p> Al ejercer los Derechos con licencia (definidos a continuación), usted acepta y acepta regirse por los términos y condiciones de esta Licencia pública internacional Creative Commons Reconocimiento-No comercial-Compartir igual 4.0 («Licencia pública»). En la medida en que esta Licencia pública pueda interpretarse como un contrato, se le otorgan los Derechos con licencia en consideración de Su aceptación de estos términos y condiciones, y el Licenciante le otorga dichos derechos en consideración de los beneficios que el Licenciante recibe al poner a disposición el Material con licencia. bajo estos términos y condiciones.\n" +
            "\n" +
            "<p>Este es un resumen legible por humanos de (y no un sustituto) de la licencia . Descargo de responsabilidad .\n" +
            "\n" +
            "<p><h3>Eres libre de:\n" +
            "<p>Compartir : copia y redistribuye el material en cualquier medio o formato.\n" +
            "<p>Adaptarse : remezclar, transformar y construir sobre el material\n" +
            "<p>El licenciante no puede revocar estas libertades siempre que siga los términos de la licencia.\n" +
            "\n" +
            "<p><h3>Bajo los siguientes términos:\n" +
            "<p>Atribución : debe otorgar el crédito correspondiente , proporcionar un enlace a la licencia e indicar si se realizaron cambios . Puede hacerlo de cualquier manera razonable, pero no de ninguna manera que sugiera que el licenciante lo respalda a usted o su uso.\n" +
            "<p>No comercial: no puede utilizar el material con fines comerciales .\n" +
            "<p>ShareAlike : si remezcla, transforma o construye sobre el material, debe distribuir sus contribuciones bajo la misma licencia que el original.\n" +
            "<p>Sin restricciones adicionales : no puede aplicar términos legales o medidas tecnológicas que restrinjan legalmente a otros de hacer cualquier cosa que permita la licencia. <html>");
        getContentPane().add(CC_JEVG, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 580, 378));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegresarActionPerformed
        // TODO add your handling code here:
            H_Inicio inicio;  
            inicio=new H_Inicio();
            inicio.setVisible(true);
            inicio.setB_RegistroPrincipal(H_Inicio);
            dispose();  
    }//GEN-LAST:event_RegresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Z_LicenciaJEVG_CC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Z_LicenciaJEVG_CC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Z_LicenciaJEVG_CC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Z_LicenciaJEVG_CC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Z_LicenciaJEVG_CC().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CC_JEVG;
    private javax.swing.JButton Regresar;
    // End of variables declaration//GEN-END:variables
    B_RegistroPrincipal H_Inicio;
    
    public void setB_RegistroPrincipal(B_RegistroPrincipal I)
    {
        H_Inicio = I;
    }   
}
